# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"i\n\nSMARequest\x12\x13\n\x0bStockSymbol\x18\x01 \x01(\t\x12\x12\n\ntickerSize\x18\x02 \x01(\t\x12\x10\n\x08SMAShort\x18\x03 \x01(\x05\x12\x0f\n\x07SMALong\x18\x04 \x01(\x05\x12\x0f\n\x07\x63\x61pital\x18\x05 \x01(\x05\"\xbc\x01\n\x08SMAReply\x12\x15\n\rdollar_profit\x18\x01 \x01(\x02\x12\x16\n\x0epercent_profit\x18\x02 \x01(\x02\x12\x0e\n\x06prices\x18\x03 \x03(\x02\x12(\n\x07signals\x18\x04 \x03(\x0b\x32\x17.SMAReply.SignalMessage\x1aG\n\rSignalMessage\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x16\n\x0etimeSinceStart\x18\x02 \x01(\x05\x12\x10\n\x08quantity\x18\x03 \x01(\x02\x32\x35\n\rBacktesterGui\x12$\n\x08SMA_Call\x12\x0b.SMARequest\x1a\t.SMAReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SMAREQUEST']._serialized_start=17
  _globals['_SMAREQUEST']._serialized_end=122
  _globals['_SMAREPLY']._serialized_start=125
  _globals['_SMAREPLY']._serialized_end=313
  _globals['_SMAREPLY_SIGNALMESSAGE']._serialized_start=242
  _globals['_SMAREPLY_SIGNALMESSAGE']._serialized_end=313
  _globals['_BACKTESTERGUI']._serialized_start=315
  _globals['_BACKTESTERGUI']._serialized_end=368
# @@protoc_insertion_point(module_scope)
